set modeline
set ff=unix
set enc=utf-8
set tabstop=8
set shiftwidth=4
set expandtab
set autoindent
set smartindent
set backup
set writebackup
" emacs-like search for god sake
set incsearch
set ignorecase
set smartcase

syntax on

filetype plugin on

" Highlight chars that go over the 80-column limit
highlight OverLength ctermbg=darkgray guibg=darkgray
autocmd BufWinEnter * match OverLength '\%81v.*'

"flag problematic whitespace (trailing and spaces before tabs)
""Note you get the same by doing let c_space_errors=1 but
"this rule really applys to everything.
highlight RedundantSpaces term=standout ctermbg=red guibg=red
autocmd BufWinEnter * match RedundantSpaces /\s\+$\| \+\ze\t\|[^\t]\zs\t\+/
let c_space_errors=1

""use :set list! to toggle visible whitespace on/off
set listchars=tab:>-,trail:.,extends:>
set list

