# If you come from bash you might have to change your $PATH.
export LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8
export EDITOR="emacs"
case $(uname -s) in
    Darwin)
        export ANDROID_HOME="$HOME/Library/Android/sdk"
        export JAVA_HOME="/Applications/Android Studio.app/Contents/jre/Contents/Home"
        export HOMEBREW_PREFIX=/opt/homebrew
        export NVM_INSTALL_DIR="$HOMEBREW_PREFIX/opt/nvm"
        export NVM_COMPLETION="$NVM_INSTALL_DIR/etc/bash_completion.d/nvm"
        ;;
    Linux)
        export ANDROID_HOME="$HOME/Android/Sdk"
        export JAVA_HOME="/usr/lib/jvm/default"
        export HOMEBREW_PREFIX=/home/linuxbrew/.linuxbrew
        export NVM_INSTALL_DIR="/usr/share/nvm"
        export NVM_COMPLETION="$NVM_INSTALL_DIR/bash_completion"
        ;;
esac
export PATH="$HOME/bin:$HOME/.local/bin:$HOMEBREW_PREFIX/bin:$HOME/.cargo/bin:$JAVA_HOME/bin:$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/emulator:$ANDROID_HOME/platform-tools"

export PIPENV_VENV_IN_PROJECT=1

HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory autocd beep extendedglob notify

source ~/.zsh-private

if (( $+commands[pyenv] )); then
    export PYENV_ROOT="${PYENV_ROOT:-$HOME/.pyenv}"
    export PYENV_SHELL=zsh
    path=(${path:#$PYENV_ROOT/shims})
    path=("$PYENV_ROOT/shims" $path)

    function pyenv() {
        local command=${1:-}
        (( $# )) && shift

        case "$command" in
            rehash|shell) eval "$(command pyenv "sh-$command" "$@")" ;;
            *) command pyenv "$command" "$@" ;;
        esac
    }
fi

if (( $+commands[rbenv] )); then
    export RBENV_ROOT="${RBENV_ROOT:-$HOME/.rbenv}"
    export RBENV_SHELL=zsh
    path=(${path:#$RBENV_ROOT/shims})
    path=("$RBENV_ROOT/shims" $path)

    function rbenv() {
        local command=${1:-}
        (( $# )) && shift

        case "$command" in
            rehash|shell) eval "$(command rbenv "sh-$command" "$@")" ;;
            *) command rbenv "$command" "$@" ;;
        esac
    }

    alias rubies="rbenv versions"
    alias gemsets="rbenv gemset list"
fi

ZSH_COMPLETION_CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/zsh/completions"
ZSH_COMPDUMP="$ZSH_COMPLETION_CACHE_DIR/.zcompdump"

function _cache-zsh-completion() {
    local name=${1:?Missing completion name}
    shift
    local target="$ZSH_COMPLETION_CACHE_DIR/_$name"
    local generated="$target.$$.generated"
    local temporary="$target.$$.tmp"

    if ! "$@" >| "$generated" ||
       ! command awk 'found || /^#compdef([[:space:]]|$)/ { found=1; print } END { exit !found }' "$generated" >| "$temporary"; then
        command rm -f -- "$generated" "$temporary"
        return 1
    fi

    command rm -f -- "$generated"
    command mv -f -- "$temporary" "$target"
}

function refresh-zsh-completions() {
    local result=0
    command mkdir -p -- "$ZSH_COMPLETION_CACHE_DIR" || return

    (( $+commands[opencode] )) && { _cache-zsh-completion opencode opencode completion zsh || result=1 }
    (( $+commands[codex] )) && { _cache-zsh-completion codex codex completion zsh || result=1 }
    (( $+commands[openclaw] )) && { _cache-zsh-completion openclaw openclaw completion --shell zsh || result=1 }
    (( $+commands[grok] )) && { _cache-zsh-completion grok grok completions zsh || result=1 }
    (( $+commands[pnpm] )) && { _cache-zsh-completion pnpm pnpm completion zsh || result=1 }
    (( $+commands[gog] )) && { _cache-zsh-completion gog gog completion zsh || result=1 }

    command rm -f -- "$ZSH_COMPDUMP" "$ZSH_COMPDUMP.zwc"
    return $result
}

for completion in opencode codex openclaw grok pnpm gog; do
    if (( $+commands[$completion] )) && [[ ! -s "$ZSH_COMPLETION_CACHE_DIR/_$completion" ]]; then
        refresh-zsh-completions
        break
    fi
done
unset completion

fpath=(
    "$ZSH_COMPLETION_CACHE_DIR"
    $fpath
)
# Path to your oh-my-zsh installation.
  export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes

#  ZSH_THEME="agnoster"
  ZSH_THEME="k-s"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
#  ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
  COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
  HIST_STAMPS="yyyy-mm-dd"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git emacs history-substring-search colorize safe-paste urltools virtualenv yarn npm docker docker-compose)
(( $+commands[aws] )) && plugins+=(aws)

source $ZSH/oh-my-zsh.sh

# cache for slow commands
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path ~/.zsh/cache
zstyle ':completion:*' rehash true

# Fuzzy matching of completions for when you mistype them
zstyle ':completion:*' completer _complete _match _approximate
zstyle ':completion:*:match:*' original only
zstyle ':completion:*:approximate:*' max-errors 1 numeric

# kill completes usign a menu
zstyle ':completion:*:*:kill:*' menu yes select
zstyle ':completion:*:kill:*'   force-list always

# squeeze-slashes removes trailing slashes
zstyle ':completion:*' squeeze-slashes true

# cd will never select the parent directory (e.g.: cd ../<TAB>):
zstyle ':completion:*:cd:*' ignore-parents parent pwd

export CLICOLOR=1
export LSCOLORS=ExGxcxdxcxegedabagacad

# git-diff-branches refrence..other
alias git-diff-branches='git log --left-right --graph --cherry-pick --oneline'

alias rn-i='react-native run-ios'
alias rn-a='react-native run-android'

alias py=ipython

function android-emulators() {
    (cd ~/.android/avd/ && ls -1d *.avd | sed 's:[.]avd$::g')
}

function android-emulator() {
    EMULATOR=${1:?Missing emulator name, see android-emulators}
    (cd $ANDROID_HOME/emulator && ./emulator -avd $EMULATOR &)
}

# helper to: git reset --hard [branch]
# defaults to origin/master
function grst() {
    local branch=${1:-origin/master}
    if [[ "$branch" != */* ]]; then
        branch="origin/$branch"
    elif [[ "$branch" == local/* ]]; then
        branch=${branch/local\//}
    fi
    git reset --hard "${branch}" &&
        echo "reseted git to branch $branch" >&2
}

# test some branch using the local "test" branch
# helper to: git checkout test && git reset --hard <branch>
function gtst() {
    local branch=${1?missing branch to test}
    if [[ "$branch" != */* ]]; then
        branch="origin/$branch"
    elif [[ "$branch" == local/* ]]; then
        branch=${branch/local\//}
    fi
    git checkout test &&
        git reset --hard "${branch}" &&
        echo "testing git branch $branch" >&2
}

# git merge, push & delete
# gmpd <local-branch> <push-to-master-branch> <remote>
function gmpd() {
    local branch=${1?missing branch to merge and delete}
    local master=${2?missing master branch to merge on}
    local remote=${3:-origin}
    if [ -z "$master" -o -z "$remote" -o "$branch" = "$master" ]; then
        echo "invalid parameters: $*" 1>&2
        return 1
    fi
    git fetch ${remote} &&
        git checkout ${master} &&
        git reset --hard ${remote}/${master} &&
        git merge --ff-only ${branch} &&
        git push ${remote} &&
        git push --no-verify ${remote} :${branch} &&
        git branch -d ${branch}
}

# gmpd to `main`
function gmpd-main() {
    gmpd ${1} main ${2}
}

# gmpd to `master`
function gmpd-master() {
    gmpd ${1} master ${2}
}

# gmpd to `develop`
function gmpd-develop() {
    gmpd ${1} develop ${2}
}

# git fetch, rebase, merge, push & delete
# grmpd <local-branch> <push-to-master-branch> <remote>
function grmpd() {
    local branch=${1?missing branch to merge and delete}
    local master=${2?missing master branch to merge on}
    local remote=${3:-origin}
    if [ -z "$master" -o -z "$remote" -o "$branch" = "$master" ]; then
        echo "invalid parameters: $*" 1>&2
        return 1
    fi
    git fetch ${remote} &&
        git checkout ${branch} &&
        git rebase ${remote}/${master} &&
        git push --no-verify --force --set-upstream ${remote} ${branch} &&
        git checkout ${master} &&
        git reset --hard ${remote}/${master} &&
        git merge --ff-only ${branch} &&
        git push ${remote} &&
        git push --no-verify ${remote} :${branch} &&
        git branch -d ${branch}
}

function grmpd-master() {
    grmpd ${1} master ${2}
}

function grmpd-develop() {
    grmpd ${1} develop ${2}
}

# git remote add github repository handles (user:branch)
# useful to copy from GitHub web ui
function gra-github() {
    local user=${1?missing GitHub user:branch}
    local branch=${2}
    if [ -z "$branch" ]; then
        branch=`echo "$user" | cut -d: -f2`
        if [ -n "$branch" -a "$branch" != "$user" ]; then
            user=`echo "$user" | cut -d: -f1`
        else
            branch=`echo "$user" | cut -d/ -f2`
            if [ - "$branch" -a "$branch" != "$user" ]; then
                user=`echo "$user" | cut -d/ -f1`
            else
                branch="master"
            fi
        fi
    fi
    local origin=`git config --get remote.origin.url`
    if [ -z "$origin" ]; then
        echo "ERROR: could not get remote.origin.url" >&2
        return 1
    fi
    local reponame=`basename ${origin} | cut -d. -f1`
    if [ -z "$reponame" ]; then
        echo "ERROR: could not find remote reponame from origin" >&2
        return 1
    fi
    git remote add $user git@github.com:${user}/${reponame}.git
    if ! git fetch $user ${branch}; then
        echo "ERROR: failed to add repository ${user}/${reponame}, branch ${branch}" >&2
        git remote rm $user
        return 1
    fi
    echo "added ${user}/${reponame}, check branch ${user}/${branch}"
}

export NVM_DIR="$HOME/.nvm"
NVM_LAZY_COMMANDS=(nvm node npm npx pnpm pnpx yarn corepack)
NVM_LAZY_LOADED=0
NVMRC_ACTIVE_PATH=""

function _load-nvm() {
    (( NVM_LAZY_LOADED )) && return
    [[ -s "$NVM_INSTALL_DIR/nvm.sh" ]] || return 1

    local command
    for command in $NVM_LAZY_COMMANDS; do
        unfunction "$command" 2>/dev/null
    done

    path=(${path:#${NVM_DIR}/versions/node/*/bin})
    unset NVM_BIN NVM_INC

    source "$NVM_INSTALL_DIR/nvm.sh" || return
    [[ -s "$NVM_COMPLETION" ]] && source "$NVM_COMPLETION"
    NVM_LAZY_LOADED=1
    nvm use default --silent >/dev/null 2>&1
    return 0
}

for nvm_lazy_command in $NVM_LAZY_COMMANDS; do
    eval "function $nvm_lazy_command() { _load-nvm || return; $nvm_lazy_command \"\$@\"; }"
done
unset nvm_lazy_command

function _find-nvmrc() {
    local directory=$PWD

    while [[ "$directory" != / ]]; do
        if [[ -f "$directory/.nvmrc" ]]; then
            REPLY="$directory/.nvmrc"
            return
        fi
        directory=${directory:h}
    done

    [[ -f /.nvmrc ]] || return 1
    REPLY=/.nvmrc
}

function _load-nvm-for-directory() {
    if _find-nvmrc; then
        [[ "$REPLY" == "$NVMRC_ACTIVE_PATH" ]] && return
        local nvmrc_path=$REPLY
        local requested_version=$(<"$nvmrc_path")
        _load-nvm || return
        NVMRC_ACTIVE_PATH=$nvmrc_path

        if [[ "$(nvm version "$requested_version")" == N/A ]]; then
            print -u2 -- "nvm: $requested_version from $nvmrc_path is not installed; run 'nvm install' in that directory"
            return 0
        fi

        nvm use "$requested_version" --silent || return 0
    elif (( NVM_LAZY_LOADED )) && [[ -n "$NVMRC_ACTIVE_PATH" ]]; then
        nvm use default --silent
        NVMRC_ACTIVE_PATH=""
    fi
}

autoload -U add-zsh-hook
add-zsh-hook chpwd _load-nvm-for-directory
_load-nvm-for-directory

export OPENCODE_EXPERIMENTAL_LSP_TOOL=true
export OPENCODE_ENABLE_EXA=true
