#!/bin/sh /etc/rc.common

START=99

USE_PROCD=1
PACKAGE=wireless
TYPE=wifi-disconnect-low-signal
NAME="${TYPE}.lua"
PROG="/usr/bin/${TYPE}.lua"

VERBOSITY=""
VERBOSITY_DEFAULT=0
STDERR=""
STDERR_DEFAULT=0

validate_wifi_disconnect_low_signal_section() {
	uci_load_validate "$PACKAGE" "$TYPE" "$1" "$2" \
		"verbosity:range(0,3)" \
		"stderr:bool"
}

# This function runs for each `config wifi-disconnect-low-signal` section that
# appears in `/etc/config/wireless`.  Settings from later sections take
# precedence over settings from earlier sections.
configure_wifi_disconnect_low_signal() {
	if [ "${2:-1}" != 0 ]; then
		echo "validation failed"
		return "${2:-1}"
	fi

	if [ -n "$verbosity" ]; then
		VERBOSITY="$verbosity"
	fi

	if [ -n "$stderr" ]; then
		STDERR="$stderr"
	fi
}

start_wifi_disconnect_low_signal() {
	VERBOSITY="${VERBOSITY:-${VERBOSITY_DEFAULT}}"
	STDERR="${STDERR:-${STDERR_DEFAULT}}"

	procd_open_instance
	procd_set_param command "$PROG"

	verbosity_counter=0
	while [ "$verbosity_counter" -lt "$VERBOSITY" ]; do
		procd_append_param command -v
		verbosity_counter="$(( verbosity_counter + 1 ))"
	done

	if [ "$STDERR" != 0 ]; then
		procd_append_param command --stderr
	fi

        procd_set_param file "/etc/config/${PACKAGE}"
	procd_set_param respawn "${respawn_threshold:-3600}" "${respawn_timeout:-5}" "${respawn_retry:-5}"
	procd_close_instance
}

start_service() {
	config_load "$PACKAGE"
	config_foreach validate_wifi_disconnect_low_signal_section "$TYPE" \
		configure_wifi_disconnect_low_signal
	start_wifi_disconnect_low_signal
}

reload_service() {
	stop
	start
}

service_triggers() {
	procd_add_validation validate_wifi_disconnect_low_signal_section
}
